services:
  redirectionListener:
    class: OC\ProductBundle\Listener\RedirectionListener
    arguments: ["@service_container","@session"]
    tags:
      - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }

   
    