<?php

namespace OC\OnlineCvBundle\Repository;

/**
 * LoisirsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LoisirsRepository extends \Doctrine\ORM\EntityRepository
{
}
