<?php

namespace OC\OnlineCvBundle\Repository;

/**
 * TheResumeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TheResumeRepository extends \Doctrine\ORM\EntityRepository
{
	public function recherche($chaine)
    {
         $qb = $this->createQueryBuilder('t')
                    ->select('t')
                    ->where('t.objet like :chaine')
                    ->orderBy('t.id')
                    ->setParameter('chaine', $chaine);
        return $qb->getQuery()->getResult();
    }

   public function findByThisV($valid)
{
  $qb = $this->createQueryBuilder('t');
  $qb->where('t.valid = :valid')
       ->setParameter('valid', $valid)
     ->orderBy('t.date', 'DESC');

  return $qb
    ->getQuery()
    ->getResult();
  
}	
}
