oc_commandes_homepage:
    path:     /page
    defaults: { _controller: OCCommandesBundle:Default:index }
       
oc_commandes_validation:
    path:      /api/banque/{id}
    defaults:
        _controller: OCCommandesBundle:Commandes:validationCommande
    requirements:
        id: \d+
        

oc_commandes_lesCommandes:
    path:     /lesCommandes
    defaults: { _controller: OCCommandesBundle:Commandes:lesCommandes }        

