# src/OC/PlatformBundle/Resources/config/routing.yml

oc_platform_home:
    path: /
    defaults:
        _controller: OCCoreBundle:Core:index
        
oc_platform_look:
    path:       /look
    defaults:
        _controller: OCPlatformBundle:Advert:look
        
oc_platform_checkin:
    path:      /checkin
    defaults:
        _controller: OCPlatformBundle:Advert:checkin
        
oc_platform_validation:
    path:      /preAdvert/{id}
    defaults:
        _controller: OCPlatformBundle:Advert:validation
    requirements:
        id: \d+   

oc_platform_decliner:
    path:      /decliner/{id}
    defaults:
        _controller: OCPlatformBundle:Advert:decliner
    requirements:
        id: \d+ 

oc_platform_valid:
    path:      /valid/{id}
    defaults:
        _controller: OCPlatformBundle:Advert:valid
    requirements:
        id: \d+                
    
oc_platform_view:
    path:      /advert/{id}
    defaults:
        _controller: OCPlatformBundle:Advert:view
    requirements:
        id: \d+
        
oc_platform_add:
    path:      /add
    defaults:
        _controller: OCPlatformBundle:Advert:add

oc_platform_edit:
    path:      /edit/{id}
    defaults:
        _controller: OCPlatformBundle:Advert:edit
    requirements:
        id: \d+

oc_platform_delete:
    path:      /delete/{id}
    defaults:
        _controller: OCPlatformBundle:Advert:delete
    requirements:
        id: \d+

oc_platform_apply: 
    path:      /apply/{id}
    defaults:
        _controller: OCPlatformBundle:Application:apply
    requirements:
        id: \d+  

oc_platform_candidat:
    path:      /candidat
    defaults:
        _controller: OCPlatformBundle:Application:candidat        
        
oc_platform_purge:
    path:     /purge/{days}
    defaults:
        _controller: OCPlatformBundle:Advert:purge
    requirements:
        days: \d+

oc_platform_paramconverter:
  path: /test/{json}
  defaults:
    _controller: "OCPlatformBundle:Advert:ParamConverter"
