<?php

namespace OC\BoutiqueBundle\Repository;

/**
 * BoutiqueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BoutiqueRepository extends \Doctrine\ORM\EntityRepository
{
	public function recherche($chaine)
    {
         $qb = $this->createQueryBuilder('b')
                    ->select('b')
                    ->where('b.name like :chaine')
                    ->orderBy('b.id')
                    ->setParameter('chaine', $chaine);
        return $qb->getQuery()->getResult();
    }	
}
