<?php

namespace OC\BoutiqueBundle\Repository;

/**
 * TarificationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TarificationRepository extends \Doctrine\ORM\EntityRepository
{
}
