<?php

namespace OC\CommandesBundle\Repository;

/**
 * AnnexeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnnexeRepository extends \Doctrine\ORM\EntityRepository
{
	public function getPbyBout($thisC)
    {
        $qb = $this->createQueryBuilder('a')
				->select('SUM(a.casePoids) AS totalP, SUM(a.casePrix) AS totalMo, a.caseIdB')
                ->where('a.commande = :commande')
                ->groupBy('a.caseIdB')
                ->setParameter('commande', $thisC);
        
        return $qb->getQuery()->getScalarResult();
    }
	
	public function calCulTva($thisCom)
    {
        $qb = $this->createQueryBuilder('a')
				->select('SUM(a.valeurTva) AS totalTva, a.caseTva')
                ->where('a.commande = :commande')
                ->groupBy('a.caseTva')
                ->setParameter('commande', $thisCom);
        
        return $qb->getQuery()->getScalarResult();
    }
	
	public function getNameP($thisId)
    {
        $qb = $this->createQueryBuilder('a')
				->select('a.caseName, a.caseQte, a.taille, a.couleur')
                ->where('a.caseIdB = :caseIdB')
                ->setParameter('caseIdB', $thisId);
        
        return $qb->getQuery()->getScalarResult();
    }
	
	
	
}
