<?php

namespace OC\CommandesBundle\Repository;

/**
 * CommandesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommandesRepository extends \Doctrine\ORM\EntityRepository
{
	public function byFacture($user)
    {
        $qb = $this->createQueryBuilder('c')
                ->select('c')
                ->where('c.user = :user')
                ->andWhere('c.valider = 1')
                ->andWhere('c.reference != 0')
                ->orderBy('c.id')
                ->setParameter('user', $user);
        
        return $qb->getQuery()->getResult();
    }
	
	public function lesCommand()
    {
        $qb = $this->createQueryBuilder('c')
                ->select('c')
                ->where('c.valider = 1')
                ->andWhere('c.reference != 0')
                ->orderBy('c.date', 'DESC');
        return $qb->getQuery()->getResult();
    }
}
