oc_pub:
    resource: "@OCPubBundle/Resources/config/routing.yml"
    prefix:   /pub

oc_recherche:
    resource: "@OCRechercheBundle/Resources/config/routing.yml"
    prefix:   /recherch

oc_annonce:
    resource: "@OCAnnonceBundle/Resources/config/routing.yml"
    prefix:   /annonce


oc_commandes:
    resource: "@OCCommandesBundle/Resources/config/routing.yml"
    prefix:   /command


oc_adress:
    resource: "@OCAdressUtilisaBundle/Resources/config/routing.yml"
    prefix:   /adress

oc_product:
    resource: "@OCProductBundle/Resources/config/routing.yml"
    prefix:   /product
    
oc_online_cv:
    resource: "@OCOnlineCvBundle/Resources/config/routing.yml"
    prefix:   /resume


oc_platform:
    resource: "@OCPlatformBundle/Resources/config/routing.yml"
    prefix:   /platform

oc_boutique:
    resource: "@OCBoutiqueBundle/Resources/config/routing.yml"
    prefix:   /shoping
    
oc_user:
    resource: "@OCUserBundle/Resources/config/routing.yml"
    prefix:   /

# On inclut également les routes de notre CoreBundle, sans préfixe
oc_core:
    resource: "@OCCoreBundle/Resources/config/routing.yml"

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile
    

