<?php

namespace OC\PubBundle\Repository;

/**
 * BanniLargeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BanniLargeRepository extends \Doctrine\ORM\EntityRepository
{
}
